[package]
name = "obj"
version = "0.1.1"
authors = ["gfaster"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
nalgebra = "0.32.2"
nalgebra-glm = "0.18.0"
